import { test, expect, type Page } from '@playwright/test'
import { command, state, resetShow } from './helpers'

// The Looks library (saved presets) under the monitors, and the per-screen scene editor on the right.

async function clean() {
  await resetShow()
  // Reset keeps the preset library, the rundowns and the tournaments; start (and leave) every test with none of them.
  const s = await state()
  for (const k of s.stacks) await command({ type: 'deleteStack', id: k.id })
  for (const p of s.presets) await command({ type: 'deletePreset', id: p.id })
  for (const t of s.tournaments) await command({ type: 'deleteTournament', id: t.id })
}
test.beforeEach(clean)
test.afterAll(clean)

const tile = (page: Page, id: string) => page.locator(`[data-look-tile=${id}]`)
const manage = async (page: Page, id: string) => page.locator(`[data-manage=${id}]`).click()
const undoLast = (page: Page) => page.locator('[data-toast] [data-undo]').last().click()
const update = (page: Page) => page.locator('[data-update-look]')
const wideLayers = async () => (await state()).layers.wide

/** Two looks (line-up, standings) saved from Preview, the second one loaded. Wide is the only armed output. */
async function seedTwoLooks() {
  await command({ type: 'arm', outputIds: ['wide'] })
  await command({ type: 'setLayers', outputId: 'wide', patch: { scene: 'lineup' } })
  await command({ type: 'savePreset', name: 'Lineup look' })
  await command({ type: 'setLayers', outputId: 'wide', patch: { scene: 'standings' } })
  await command({ type: 'savePreset', name: 'Standings look' })
}

test.describe('library', () => {
  test('empty state, then a tile per saved look with its cue count', async ({ page }) => {
    await page.goto('/control')
    await expect(page.locator('[data-looks-empty]')).toContainText('No looks yet')
    await expect(page.locator('[data-look-count]')).toHaveText('0')
    await command({ type: 'savePreset', name: 'A' })
    await command({ type: 'savePreset', name: 'B' })
    await command({ type: 'createStack', name: 'Run' })
    await command({ type: 'addCue', stackId: 'stack-1', presetId: 'preset-1', take: null })
    await command({ type: 'addCue', stackId: 'stack-1', presetId: 'preset-1', take: 'cut' })
    await expect(page.locator('[data-look-tile]')).toHaveCount(2)
    await expect(page.locator('[data-look-count]')).toHaveText('2')
    await expect(tile(page, 'preset-1')).toContainText('2 cues')
    await expect(tile(page, 'preset-2')).toContainText('no cue')
  })

  test('tapping a tile loads the look into Preview only: Program does not change', async ({ page }) => {
    await seedTwoLooks()
    await command({ type: 'take', mode: 'cut' }) // standings on air
    await command({ type: 'setLayers', outputId: 'wide', patch: { scene: 'none' } })
    await page.goto('/control')
    await page.locator('[data-look=preset-1]').click()
    await expect.poll(async () => (await wideLayers()).scene).toBe('lineup')
    const s = await state()
    expect(s.lastPreset).toBe('preset-1')
    expect(s.program.wide.view.scene?.kind).toBe('standings')
    await expect(tile(page, 'preset-1')).toContainText('IN PREVIEW')
    await expect(tile(page, 'preset-2')).not.toContainText('IN PREVIEW')
    await expect(page.locator('[data-look-status]')).toContainText('Lineup look')
    await expect(page.locator('[data-saved]')).toBeVisible()
    // undo puts Preview back exactly as it was
    await expect(page.locator('[data-toast]').last()).toContainText('Loaded “Lineup look” into Preview')
    await undoLast(page)
    await expect.poll(async () => (await wideLayers()).scene).toBe('none')
    expect((await state()).lastPreset).toBe('preset-2')
  })

  test('marks the look that is on air and the look in Preview', async ({ page }) => {
    await seedTwoLooks()
    await command({ type: 'take', mode: 'cut' })
    await page.goto('/control')
    await expect(tile(page, 'preset-2').locator('[data-tag=on-air]')).toBeVisible()
    await expect(tile(page, 'preset-2').locator('[data-tag=in-preview]')).toBeVisible()
    await expect(tile(page, 'preset-1').locator('[data-tag=on-air]')).toHaveCount(0)
    await page.locator('[data-look=preset-1]').click()
    await expect(tile(page, 'preset-1').locator('[data-tag=in-preview]')).toBeVisible()
    await expect(tile(page, 'preset-2').locator('[data-tag=in-preview]')).toHaveCount(0)
    await expect(tile(page, 'preset-2').locator('[data-tag=on-air]')).toBeVisible()
    // the Program monitor names the look on air, the Preview monitor the loaded one
    await expect(page.locator('[data-monitor=program]')).toContainText('Standings look')
    await expect(page.locator('[data-monitor=preview]')).toContainText('Lineup look')
  })

  test('filter narrows the tiles and says when nothing matches', async ({ page }) => {
    for (const name of ['Standings', 'Title card', 'Line-up reveal']) await command({ type: 'savePreset', name })
    await page.goto('/control')
    await expect(page.locator('[data-look-tile]')).toHaveCount(3)
    const f = page.locator('input[name=lookFilter]')
    await f.fill('tit')
    await expect(page.locator('[data-look-tile]')).toHaveCount(1)
    await expect(tile(page, 'preset-2')).toBeVisible()
    await f.fill('LINE')
    await expect(page.locator('[data-look-tile]')).toHaveCount(1)
    await expect(tile(page, 'preset-3')).toBeVisible()
    await f.fill('zzz')
    await expect(page.locator('[data-look-tile]')).toHaveCount(0)
    await expect(page.locator('[data-looks-empty]')).toContainText('No looks match')
    await f.fill('')
    await expect(page.locator('[data-look-tile]')).toHaveCount(3)
  })
})

test.describe('modified, update and revert', () => {
  test('MODIFIED appears after a scene change and clears after Update (two taps, with Undo)', async ({ page }) => {
    await command({ type: 'setLayers', outputId: 'wide', patch: { scene: 'lineup' } })
    await command({ type: 'savePreset', name: 'A' })
    await command({ type: 'createStack', name: 'Run' })
    await command({ type: 'addCue', stackId: 'stack-1', presetId: 'preset-1', take: 'cut' })
    await command({ type: 'addCue', stackId: 'stack-1', presetId: 'preset-1', take: 'auto' })
    await page.goto('/control')
    await expect(page.locator('[data-saved]').first()).toBeVisible()
    await expect(update(page)).toBeDisabled()
    await expect(page.locator('[data-revert]')).toBeDisabled()

    await page.locator('[data-scene=standings]').click()
    await expect(page.locator('[data-modified]').first()).toBeVisible()
    await expect(tile(page, 'preset-1').locator('[data-tag=modified]')).toBeVisible()
    await expect(page.locator('[data-monitor=preview]')).toContainText('MODIFIED')
    await expect(page.locator('[data-look-based]')).toContainText('MODIFIED')
    await expect(update(page)).toBeEnabled()
    await expect(update(page)).toContainText('Update “A”')

    // first tap only arms it (amber, says how many cues it affects); nothing is overwritten yet
    await update(page).click()
    await expect(update(page)).toContainText('Tap again to overwrite')
    await expect(update(page)).toContainText('affects 2 cues')
    expect((await state()).presets[0].layers.wide.scene).toBe('lineup')
    await update(page).click()
    await expect.poll(async () => (await state()).presets[0].layers.wide.scene).toBe('standings')
    await expect(page.locator('[data-saved]').first()).toBeVisible()
    await expect(update(page)).toBeDisabled()
    await expect(page.locator('[data-toast]').last()).toContainText('Updated “A” — used by 2 cues')

    await undoLast(page)
    await expect.poll(async () => (await state()).presets[0].layers.wide.scene).toBe('lineup')
    await expect(page.locator('[data-modified]').first()).toBeVisible()
  })

  test('the armed Update disarms when the Preview state changes under it', async ({ page }) => {
    await command({ type: 'savePreset', name: 'A' })
    await page.goto('/control')
    await page.locator('[data-scene=standings]').click()
    await update(page).click()
    await expect(update(page)).toContainText('Tap again')
    await page.locator('[data-scene=title]').click() // back to what the look has
    await expect(update(page)).toBeDisabled()
    await expect(update(page)).not.toContainText('Tap again')
    expect((await state()).presets[0].layers.wide.scene).toBe('title')
  })

  test('Revert loads the look again, discarding the changes (and can be undone)', async ({ page }) => {
    await command({ type: 'setLayers', outputId: 'wide', patch: { scene: 'lineup' } })
    await command({ type: 'savePreset', name: 'A' })
    await command({ type: 'setLayers', outputId: 'wide', patch: { scene: 'standings', background: 'C' } })
    await page.goto('/control')
    await expect(page.locator('[data-look-based]')).toContainText('MODIFIED')
    await page.locator('[data-revert]').click()
    await expect.poll(async () => (await wideLayers()).scene).toBe('lineup')
    expect((await wideLayers()).background).toBe('A')
    await expect(page.locator('[data-look-based]')).toContainText('SAVED')
    await expect(page.locator('[data-revert]')).toBeDisabled()
    await undoLast(page)
    await expect.poll(async () => (await wideLayers()).scene).toBe('standings')
  })

  test('a scene change on a part the look does not recall is not "modified"', async ({ page }) => {
    await command({ type: 'savePreset', name: 'Arming only', scope: { layers: false } })
    await page.goto('/control')
    await expect(page.locator('[data-saved]').first()).toBeVisible()
    await page.locator('[data-scene=standings]').click()
    await expect.poll(async () => (await wideLayers()).scene).toBe('standings')
    await expect(page.locator('[data-saved]').first()).toBeVisible()
    await expect(page.locator('[data-modified]')).toHaveCount(0)
  })
})

test.describe('save as new', () => {
  test('inline form: suggested name, all-screens note, default groups, saves the full scope; Undo deletes it', async ({ page }) => {
    await command({ type: 'setLayers', outputId: 'wide', patch: { scene: 'standings' } })
    await command({ type: 'arm', outputIds: ['wide', 'twins'] })
    await page.goto('/control')
    await page.locator('[data-save-open]').click()
    const form = page.locator('[data-save-form]')
    await expect(form).toBeVisible()
    await expect(page.locator('[data-scene-editor]')).toHaveCount(0) // the form replaces the scene editor; the library stays
    await expect(page.locator('[data-library]')).toBeVisible()
    await expect(form.locator('input[name=lookName]')).toHaveValue('Standings')
    await expect(form.locator('[data-save-note]')).toContainText('Saves all 4 screens (Wide, Twins, Stream, Pillars), not just Wide')
    await expect(form.locator('[data-group=look]')).toHaveAttribute('aria-pressed', 'true')
    await expect(form.locator('[data-group=outputs]')).toHaveAttribute('aria-pressed', 'true')
    await expect(form.locator('[data-group=race]')).toHaveAttribute('aria-pressed', 'false')
    await expect(form.locator('[data-group=scores]')).toHaveAttribute('aria-pressed', 'false')
    await expect(form.locator('[data-save-from=pvw]')).toHaveAttribute('aria-pressed', 'true')

    await form.locator('input[name=lookName]').fill('League table')
    await form.locator('[data-save-submit]').click()
    await expect.poll(async () => (await state()).presets.length).toBe(1)
    const s = await state()
    expect(s.presets[0]).toMatchObject({ id: 'preset-1', name: 'League table', armed: ['wide', 'twins'] })
    // the full 8-key scope is sent explicitly (the server default has Race and Players on)
    expect(s.presets[0].scope).toEqual({ layers: true, armed: true, style: true, match: false, players: false, scores: false, transition: true, mattify: true })
    expect(s.lastPreset).toBe('preset-1')
    await expect(page.locator('[data-save-form]')).toHaveCount(0)
    await expect(page.locator('[data-scene-editor]')).toBeVisible()
    await expect(tile(page, 'preset-1')).toContainText('League table')
    await expect(page.locator('[data-toast]').last()).toContainText('Saved look “League table”')
    await undoLast(page)
    await expect.poll(async () => (await state()).presets.length).toBe(0)
  })

  test('groups and the advanced parts choose the recall scope', async ({ page }) => {
    await page.goto('/control')
    await page.locator('[data-save-open]').click()
    const form = page.locator('[data-save-form]')
    await form.locator('[data-group=race]').click()
    await form.locator('[data-group=scores]').click()
    await form.locator('[data-group=outputs]').click()
    await form.locator('[data-advanced]').click()
    await form.locator('[data-scope=mattify]').click()
    await expect(form.locator('[data-scope=match]')).toHaveAttribute('aria-pressed', 'true')
    await expect(form.locator('[data-scope=mattify]')).toHaveAttribute('aria-pressed', 'false')
    await expect(form.locator('[data-group=look]')).toHaveAttribute('aria-pressed', 'false') // one part off: the group is no longer fully on
    await form.locator('input[name=lookName]').fill('Custom')
    await form.locator('[data-save-submit]').click()
    await expect.poll(async () => (await state()).presets.length).toBe(1)
    expect((await state()).presets[0].scope).toEqual({ layers: true, armed: false, style: true, match: true, players: true, scores: true, transition: true, mattify: false })
  })

  test('Cancel and Back close the form without saving', async ({ page }) => {
    await page.goto('/control')
    await page.locator('[data-save-open]').click()
    await page.locator('[data-save-form] input[name=lookName]').fill('Nope')
    await page.locator('[data-save-form] [data-save-cancel]').first().click()
    await expect(page.locator('[data-save-form]')).toHaveCount(0)
    await page.locator('[data-save-open]').click()
    await page.locator('[data-save-form] input[name=lookName]').press('Escape')
    await expect(page.locator('[data-save-form]')).toHaveCount(0)
    expect((await state()).presets).toHaveLength(0)
  })

  test('also add it to the rundown as a cue (one command), with the chosen Take; Undo removes both', async ({ page }) => {
    await command({ type: 'createStack', name: 'Run' })
    await command({ type: 'setLayers', outputId: 'wide', patch: { scene: 'standings' } })
    await page.goto('/control')
    await page.locator('[data-save-open]').click()
    const form = page.locator('[data-save-form]')
    await expect(form.locator('[data-save-add-cue]')).toContainText('Also add to “Run” as cue 1')
    await form.locator('[data-save-add-cue]').click()
    await form.locator('[data-save-take=cut]').click()
    await form.locator('input[name=lookName]').fill('Table')
    await form.locator('[data-save-submit]').click()
    await expect.poll(async () => (await state()).stacks[0].cues.length).toBe(1)
    const s = await state()
    expect(s.stacks[0].cues[0]).toMatchObject({ presetId: 'preset-1', take: 'cut' })
    expect(s.presets[0].name).toBe('Table')
    await expect(page.locator('[data-toast]').last()).toContainText('added it as cue 1 of “Run”')
    await expect(tile(page, 'preset-1')).toContainText('1 cue')
    await undoLast(page)
    await expect.poll(async () => (await state()).presets.length).toBe(0)
    expect((await state()).stacks[0].cues).toHaveLength(0)
  })

  test('save from On air now (and add a Recall-only cue): the on-air design, not Preview', async ({ page }) => {
    await command({ type: 'createStack', name: 'Run' })
    await command({ type: 'setLayers', outputId: 'wide', patch: { scene: 'lineup' } })
    await command({ type: 'arm', outputIds: ['wide'] })
    await command({ type: 'take', mode: 'cut' })
    await command({ type: 'setLayers', outputId: 'wide', patch: { scene: 'standings' } })
    await page.goto('/control')
    await page.locator('[data-save-open]').click()
    const form = page.locator('[data-save-form]')
    await form.locator('[data-save-from=pgm]').click()
    await form.locator('[data-save-add-cue]').click()
    await form.locator('[data-save-take=none]').click()
    await form.locator('input[name=lookName]').fill('On air')
    await form.locator('[data-save-submit]').click()
    await expect.poll(async () => (await state()).stacks[0].cues.length).toBe(1)
    const s = await state()
    expect(s.presets[0].layers.wide.scene).toBe('lineup')
    expect(s.stacks[0].cues[0]).toMatchObject({ presetId: 'preset-1', take: null })
    // Preview (standings) differs from what was saved (line-up), so the new look reads as modified
    await expect(page.locator('[data-modified]').first()).toBeVisible()
    await undoLast(page)
    await expect.poll(async () => (await state()).presets.length).toBe(0)
    expect((await state()).stacks[0].cues).toHaveLength(0)
  })

  test('save a design, change it, recall it', async ({ page }) => {
    await command({ type: 'setLayers', outputId: 'wide', patch: { scene: 'lineup' } })
    await command({ type: 'arm', outputIds: ['wide', 'twins'] })
    await page.goto('/control')
    await page.locator('[data-save-open]').click()
    await page.locator('[data-save-form] input[name=lookName]').fill('Lineup look')
    await page.locator('[data-save-submit]').click()
    await expect(tile(page, 'preset-1')).toContainText('Lineup look')

    await command({ type: 'setLayers', outputId: 'wide', patch: { scene: 'none' } })
    await command({ type: 'arm', outputIds: [] })
    await page.locator('[data-look=preset-1]').click()
    await expect.poll(async () => (await wideLayers()).scene).toBe('lineup')
    const s = await state()
    expect(s.armed).toEqual(['wide', 'twins'])
    expect(s.program.wide.view.scene).toBeNull() // loading never takes
    await page.getByRole('button', { name: /^CUT/ }).click()
    await expect.poll(async () => (await state()).program.wide.view.scene?.kind).toBe('lineup')
  })

  test('save from On air, then overwrite from Preview', async ({ page }) => {
    await command({ type: 'setLayers', outputId: 'wide', patch: { scene: 'lineup' } })
    await command({ type: 'arm', outputIds: ['wide'] })
    await command({ type: 'take', mode: 'cut' })
    await command({ type: 'setLayers', outputId: 'wide', patch: { scene: 'standings' } })
    await page.goto('/control')
    await page.locator('[data-save-open]').click()
    await page.locator('[data-save-form] input[name=lookName]').fill('On air')
    await page.locator('[data-save-from=pgm]').click()
    await page.locator('[data-save-submit]').click()
    await expect.poll(async () => (await state()).presets[0]?.layers.wide.scene).toBe('lineup')
    await update(page).click()
    await update(page).click()
    await expect.poll(async () => (await state()).presets[0].layers.wide.scene).toBe('standings')
  })
})

test.describe('manage', () => {
  test('rename inline (Enter), undoable', async ({ page }) => {
    await command({ type: 'savePreset', name: 'A' })
    await page.goto('/control')
    await manage(page, 'preset-1')
    const bar = page.locator('[data-manage-bar]')
    await expect(bar).toContainText('not in a rundown')
    await page.locator('[data-rename]').click()
    const input = bar.locator('input[name=renameLook]')
    await input.fill('Renamed')
    await input.press('Enter')
    await expect.poll(async () => (await state()).presets[0].name).toBe('Renamed')
    await expect(bar).toContainText('Renamed')
    await undoLast(page)
    await expect.poll(async () => (await state()).presets[0].name).toBe('A')
  })

  test('duplicate puts the copy next to it; Undo removes the copy', async ({ page }) => {
    await command({ type: 'savePreset', name: 'A' })
    await command({ type: 'savePreset', name: 'B' })
    await page.goto('/control')
    await manage(page, 'preset-1')
    await page.locator('[data-duplicate]').click()
    await expect.poll(async () => (await state()).presets.map((p) => p.name)).toEqual(['A', 'A copy', 'B'])
    await expect(page.locator('[data-toast]').last()).toContainText('Duplicated “A” as “A copy”')
    await undoLast(page)
    await expect.poll(async () => (await state()).presets.map((p) => p.name)).toEqual(['A', 'B'])
  })

  test('delete is two-tap and says how many cues go with it; Undo restores the look and the cues', async ({ page }) => {
    await command({ type: 'savePreset', name: 'A' })
    await command({ type: 'savePreset', name: 'B' })
    await command({ type: 'createStack', name: 'Run' })
    await command({ type: 'addCue', stackId: 'stack-1', presetId: 'preset-1', take: 'cut', action: 'nextRace', scope: { scores: true } })
    await command({ type: 'addCue', stackId: 'stack-1', presetId: 'preset-2', take: null })
    await command({ type: 'addCue', stackId: 'stack-1', presetId: 'preset-1', take: 'auto' })
    await page.goto('/control')
    await manage(page, 'preset-1')
    await expect(page.locator('[data-manage-bar]')).toContainText('in 2 cues')
    const del = page.locator('[data-delete]')
    await expect(del).toHaveText('Delete')
    await del.click()
    await expect(del).toContainText('Tap again · removes 2 cues')
    expect((await state()).presets).toHaveLength(2) // the first tap deletes nothing
    await del.click()
    await expect.poll(async () => (await state()).presets.map((p) => p.id)).toEqual(['preset-2'])
    expect((await state()).stacks[0].cues).toHaveLength(1)
    await expect(page.locator('[data-manage-bar]')).toHaveCount(0)
    await expect(page.locator('[data-toast]').last()).toContainText('Deleted “A” and 2 cues')

    await undoLast(page)
    await expect.poll(async () => (await state()).presets.map((p) => p.id)).toEqual(['preset-1', 'preset-2'])
    const cues = (await state()).stacks[0].cues
    expect(cues.map((c) => [c.presetId, c.take, c.action, c.scope])).toEqual([
      ['preset-1', 'cut', 'nextRace', { scores: true }], ['preset-2', null, undefined, undefined], ['preset-1', 'auto', undefined, undefined],
    ])
  })

  test('delete of a look no rundown uses names no cues and the tap disarms by itself', async ({ page }) => {
    await command({ type: 'savePreset', name: 'A' })
    await page.goto('/control')
    await manage(page, 'preset-1')
    const del = page.locator('[data-delete]')
    await del.click()
    await expect(del).toContainText('Tap again to delete')
    await expect(del).toHaveText('Delete', { timeout: 6000 })
    expect((await state()).presets).toHaveLength(1)
  })

  test('Recalls: the four groups edit the look scope; Advanced shows all 8 parts; undo with Ctrl+Z', async ({ page }) => {
    await command({ type: 'savePreset', name: 'A' }) // server default: Race and Players on, Scores off
    await page.goto('/control')
    await manage(page, 'preset-1')
    await page.locator('[data-manage-bar] [data-recalls]').click()
    const ed = page.locator('[data-recall-editor]')
    await expect(ed).toContainText('When “A” is recalled it restores')
    await expect(ed.locator('[data-group=race]')).toHaveAttribute('aria-pressed', 'true')
    await expect(ed.locator('[data-group=scores]')).toHaveAttribute('aria-pressed', 'false')
    await ed.locator('[data-group=race]').click()
    await expect.poll(async () => (await state()).presets[0].scope).toMatchObject({ match: false, players: false })
    await ed.locator('[data-group=scores]').click()
    await expect.poll(async () => (await state()).presets[0].scope.scores).toBe(true)
    await ed.locator('[data-advanced]').click()
    await expect(ed.locator('[data-scope]')).toHaveCount(8)
    await ed.locator('[data-scope=mattify]').click()
    await expect.poll(async () => (await state()).presets[0].scope.mattify).toBe(false)
    await expect(ed.locator('[data-group=look]')).toHaveAttribute('aria-pressed', 'false')
    await page.keyboard.press('Control+z')
    await expect.poll(async () => (await state()).presets[0].scope.mattify).toBe(true)
    expect((await state()).presets[0].scope.scores).toBe(true)
  })

  test('scope toggles control the recall, and the preset keeps the show data', async ({ page }) => {
    await command({ type: 'setPlayer', index: 0, patch: { name: 'SAM' } })
    await page.goto('/control')
    await page.locator('[data-save-open]').click()
    await page.locator('[data-save-form] input[name=lookName]').fill('Sam look')
    await page.locator('[data-save-form] [data-group=race]').click() // Race & players on
    await page.locator('[data-save-submit]').click()
    await expect(tile(page, 'preset-1')).toBeVisible()
    expect((await state()).presets[0].draft.players[0].name).toBe('SAM')
    await manage(page, 'preset-1')
    await page.locator('[data-manage-bar] [data-recalls]').click()
    const ed = page.locator('[data-recall-editor]')
    await ed.locator('[data-advanced]').click()
    await expect(ed.locator('[data-scope=scores]')).toHaveAttribute('aria-pressed', 'false')
    await expect(ed.locator('[data-scope=players]')).toHaveAttribute('aria-pressed', 'true')

    await command({ type: 'setPlayer', index: 0, patch: { name: 'OTHER' } })
    await page.locator('[data-look=preset-1]').click()
    await expect.poll(async () => (await state()).draft.players[0].name).toBe('SAM')

    await ed.locator('[data-scope=players]').click()
    await expect(ed.locator('[data-scope=players]')).toHaveAttribute('aria-pressed', 'false')
    await command({ type: 'setPlayer', index: 0, patch: { name: 'OTHER' } })
    await command({ type: 'setLayers', outputId: 'wide', patch: { scene: 'standings' } })
    await page.locator('[data-look=preset-1]').click()
    await expect.poll(async () => (await wideLayers()).scene).toBe('title') // the recall ran...
    expect((await state()).draft.players[0].name).toBe('OTHER') // ...but players are no longer part of it
  })

  test('＋ Cue appends the look to the rundown (undoable)', async ({ page }) => {
    await command({ type: 'savePreset', name: 'A' })
    await command({ type: 'createStack', name: 'Run' })
    await page.goto('/control')
    await manage(page, 'preset-1')
    await page.locator('[data-add-cue]').click()
    await expect.poll(async () => (await state()).stacks[0].cues.map((c) => [c.presetId, c.take])).toEqual([['preset-1', 'auto']])
    await expect(page.locator('[data-manage-bar]')).toContainText('in 1 cue')
    await expect(page.locator('[data-toast]').last()).toContainText('Added “A” as cue 1')
    await undoLast(page)
    await expect.poll(async () => (await state()).stacks[0].cues.length).toBe(0)
  })

  test('＋ Cue is disabled when there is no rundown; Done closes the bar', async ({ page }) => {
    await command({ type: 'savePreset', name: 'A' })
    await page.goto('/control')
    await manage(page, 'preset-1')
    await expect(page.locator('[data-add-cue]')).toBeDisabled()
    await page.locator('[data-manage-done]').click()
    await expect(page.locator('[data-manage-bar]')).toHaveCount(0)
    await expect(page.locator('input[name=lookFilter]')).toBeVisible()
  })

  test('each tile has a drag grip (44px target) and a manage button', async ({ page }) => {
    await command({ type: 'savePreset', name: 'A' })
    await page.goto('/control')
    const grip = await page.locator('[data-look-tile=preset-1] [aria-label^="Drag"]').boundingBox()
    expect(grip!.width).toBeGreaterThanOrEqual(44)
    expect(grip!.height).toBeGreaterThanOrEqual(44)
    const more = await page.locator('[data-manage=preset-1]').boundingBox()
    expect(more!.width).toBeGreaterThanOrEqual(44)
    expect(more!.height).toBeGreaterThanOrEqual(44)
    // the ＋ button exists only while the rundown is being edited
    await expect(page.locator('[data-add-as-cue]')).toHaveCount(0)
  })
})

test.describe('with the rundown', () => {
  async function seed() {
    for (const name of ['A', 'B', 'C']) await command({ type: 'savePreset', name })
    await command({ type: 'createStack', name: 'Run' })
    await command({ type: 'addCue', stackId: 'stack-1', presetId: 'preset-1', take: 'cut' })
    await command({ type: 'addCue', stackId: 'stack-1', presetId: 'preset-2', take: 'auto' })
  }
  const cues = async () => (await state()).stacks[0].cues.map((c) => c.presetId)

  test('the ＋ on a tile exists only while the rundown is in Edit; it appends a cue (Take: auto), undoable', async ({ page }) => {
    await seed()
    await page.goto('/control')
    await expect(page.locator('[data-add-as-cue]')).toHaveCount(0)
    await page.locator('[data-edit-toggle=edit]').click()
    await expect(page.locator('[data-add-as-cue]')).toHaveCount(3)
    const plus = (await page.locator('[data-add-as-cue=preset-3]').boundingBox())!
    expect(plus.width).toBeGreaterThanOrEqual(44)
    expect(plus.height).toBeGreaterThanOrEqual(44)
    await page.locator('[data-add-as-cue=preset-3]').click()
    await expect.poll(cues).toEqual(['preset-1', 'preset-2', 'preset-3'])
    expect((await state()).stacks[0].cues[2].take).toBe('auto')
    await expect(page.locator('[data-toast]').last()).toContainText('Added “C” as cue 3')
    await undoLast(page)
    await expect.poll(cues).toEqual(['preset-1', 'preset-2'])
    await page.locator('[data-edit-toggle=run]').click()
    await expect(page.locator('[data-add-as-cue]')).toHaveCount(0)
  })

  test('dragging a tile grip onto the rundown adds the look as a cue where it is dropped', async ({ page }) => {
    await seed()
    await page.goto('/control')
    await page.locator('[data-edit-toggle=edit]').click()
    const grip = page.locator('[data-look=preset-3] .u-grip')
    const g = (await grip.boundingBox())!
    const row = (await page.locator('[data-cue=cue-1]').boundingBox())!
    await page.mouse.move(g.x + g.width / 2, g.y + g.height / 2)
    await page.mouse.down()
    await page.mouse.move(row.x + 120, row.y + row.height - 4, { steps: 12 })
    await page.mouse.up()
    await expect.poll(cues).toEqual(['preset-1', 'preset-3', 'preset-2'])
    // the drag ended over the tile it started from, but did not also tap it (no "Loaded ..." toast)
    await expect(page.locator('[data-toast]').filter({ hasText: 'Loaded' })).toHaveCount(0)
  })

  test('the new-look form offers to add the look to the rundown on show as the next cue', async ({ page }) => {
    await seed()
    await page.goto('/control')
    await page.locator('[data-save-open]').click()
    await expect(page.locator('[data-save-add-cue]')).toContainText('Also add to “Run” as cue 3')
  })
})

test.describe('monitors', () => {
  for (const [id, name] of [['wide', 'WIDE'], ['twins', 'TWINS'], ['stream', 'STREAM']] as const)
    test(`Preview and Program sit side by side for ${id}`, async ({ page }) => {
      await page.goto('/control')
      await page.locator(`[data-output-tab=${id}]`).click()
      const pv = page.locator('[data-monitor=preview]')
      const pg = page.locator('[data-monitor=program]')
      await expect(pv).toContainText(`PREVIEW · ${name}`)
      await expect(pg).toContainText(`PROGRAM · ${name}`)
      const a = (await pv.boundingBox())!
      const b = (await pg.boundingBox())!
      expect(Math.abs(a.y - b.y)).toBeLessThan(2)
      expect(b.x).toBeGreaterThan(a.x + a.width - 1)
      // the Looks library gets the room under them
      const lib = (await page.locator('[data-library]').boundingBox())!
      expect(lib.y).toBeGreaterThan(a.y + a.height - 1)
      expect(lib.height).toBeGreaterThan(300)
      await expect(page.locator(`iframe[title="Preview ${name[0]}${name.slice(1).toLowerCase()}"]`)).toHaveAttribute('src', new RegExp(`/out/${id}\\?view=preview&lowfx=1`))
    })

  test('the Program label says ON AIR once an output page is connected, and HOLD / FTB when set', async ({ page }) => {
    await page.goto('/control')
    await expect(page.locator('[data-monitor=program]')).toContainText('PROGRAM · WIDE · ON AIR')
    await command({ type: 'hold', on: true })
    await expect(page.locator('[data-monitor=program]')).toContainText('· HOLD')
    await command({ type: 'hold', on: false })
    await command({ type: 'ftb', on: true })
    await expect(page.locator('[data-monitor=program]')).toContainText('· FTB')
    await command({ type: 'ftb', on: false })
  })
})

test.describe('scene editor', () => {
  test('follows the output tab: title, format and the scenes that screen can show', async ({ page }) => {
    await page.goto('/control')
    await expect(page.locator('[data-scene-title]')).toHaveText('Wide screen')
    await expect(page.locator('[data-scene-editor]')).toContainText('3840×1152')
    const ids = () => page.locator('[data-scene]').evaluateAll((els) => els.map((e) => e.getAttribute('data-scene')))
    expect(await ids()).toEqual(['none', 'title', 'lineup', 'announce', 'nextRace', 'standings', 'winner', 'raceWin', 'cupWin', 'notice', 'qr'])
    await page.locator('[data-output-tab=twins]').click()
    await expect(page.locator('[data-scene-title]')).toHaveText('Twins screen')
    await expect(page.locator('[data-scene-editor]')).toContainText('1920×1152')
    // a twin shows the title, QR codes and the win screens (as a hero or a board half): no line-up, standings...
    expect(await ids()).toEqual(['none', 'title', 'announce', 'raceWin', 'cupWin', 'qr'])
    await expect(page.getByRole('button', { name: 'Standings' })).toHaveCount(0)
    await page.locator('[data-output-tab=stream]').click()
    await expect(page.locator('[data-scene-title]')).toHaveText('Stream screen')
    expect(await ids()).toContain('lineup')
  })

  test('each scene button is named, pressed when chosen, and sends setLayers for the selected screen', async ({ page }) => {
    await page.goto('/control')
    const bracket = page.getByRole('button', { name: 'Bracket', exact: true })
    await expect(bracket).toHaveCount(0) // no tournament: bracket and matches are not offered
    await page.getByRole('button', { name: 'Standings', exact: true }).click()
    await expect.poll(async () => (await wideLayers()).scene).toBe('standings')
    await expect(page.getByRole('button', { name: 'Standings', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await expect(page.getByRole('button', { name: 'Title', exact: true })).toHaveAttribute('aria-pressed', 'false')
    expect((await state()).program.wide.view.scene).toBeNull() // Preview only
    await page.locator('[data-output-tab=twins]').click()
    await page.getByRole('button', { name: 'Title', exact: true }).click()
    await expect.poll(async () => (await state()).layers.twins.scene).toBe('title')
    expect((await wideLayers()).scene).toBe('standings')
  })

  test('shows a red dot on the scene and background that are on air', async ({ page }) => {
    await command({ type: 'arm', outputIds: ['wide'] })
    await command({ type: 'setLayers', outputId: 'wide', patch: { scene: 'lineup', background: 'B' } })
    await command({ type: 'take', mode: 'cut' })
    await command({ type: 'setLayers', outputId: 'wide', patch: { scene: 'standings', background: 'C' } })
    await page.goto('/control')
    await expect(page.locator('[data-scene=lineup]')).toHaveClass(/u-livedot/)
    await expect(page.locator('[data-scene=standings]')).not.toHaveClass(/u-livedot/)
    await expect(page.locator('[data-scene=standings]')).toHaveClass(/\bsel\b/)
    await expect(page.getByRole('button', { name: 'B · Icons' })).toHaveClass(/u-livedot/)
    await expect(page.getByRole('button', { name: 'C · Stickers' })).toHaveClass(/\bsel\b/)
  })

  test('options per scene: line-up, notice, QR, title, win screens, none', async ({ page }) => {
    await page.goto('/control')
    const opts = (scene: string) => page.locator(`[data-scene-options=${scene}]`)
    // line-up: Reveal + Next player
    await page.locator('[data-scene=lineup]').click()
    await expect(opts('lineup')).toContainText('Line-up options')
    await opts('lineup').getByRole('button', { name: 'P1–2', exact: true }).click()
    await expect.poll(async () => (await wideLayers()).lineupShown).toBe(2)
    await opts('lineup').locator('[data-next-player]').click()
    await expect.poll(async () => (await wideLayers()).lineupShown).toBe(3)
    await opts('lineup').getByRole('button', { name: 'All', exact: true }).click()
    await expect.poll(async () => (await wideLayers()).lineupShown).toBe(4)
    // announce: pick the player, Next player wraps P4 to P1
    await page.locator('[data-scene=announce]').click()
    await expect(opts('announce')).toContainText('Announce options')
    await opts('announce').locator('[data-announce-slot="2"]').click()
    await expect.poll(async () => (await wideLayers()).announceSlot).toBe(2)
    await opts('announce').locator('[data-next-announce]').click()
    await expect.poll(async () => (await wideLayers()).announceSlot).toBe(3)
    await opts('announce').locator('[data-next-announce]').click()
    await expect.poll(async () => (await wideLayers()).announceSlot).toBe(0)
    // a scene with none says so
    await page.locator('[data-scene=standings]').click()
    await expect(page.locator('[data-no-options]')).toHaveText('No extra options for this scene.')
    await expect(page.locator('[data-scene-options=standings]')).toContainText('Standings options')
    // notice: QR codes
    await page.locator('[data-scene=notice]').click()
    await page.getByRole('button', { name: 'Show QR codes' }).click()
    await expect.poll(async () => (await wideLayers()).noticeQr).toBe(true)
    await expect(page.getByRole('button', { name: 'Show QR codes' })).toHaveAttribute('aria-pressed', 'true')
    // QR codes: layout per format (wide has three)
    await page.locator('[data-scene=qr]').click()
    await expect(opts('qr').getByRole('button')).toHaveText(['Centre', 'Title + sides', 'Sides'])
    await opts('qr').getByRole('button', { name: 'Sides', exact: true }).click()
    await expect.poll(async () => (await wideLayers()).qrStyle).toBe('sides')
    // title: logo
    await page.locator('[data-scene=title]').click()
    await opts('title').getByRole('button', { name: 'Off', exact: true }).click()
    await expect.poll(async () => (await wideLayers()).logo).toBe('off')
    // win screens: part, split across outputs
    await page.locator('[data-scene=raceWin]').click()
    await expect(page.locator('[data-win-controls]')).toBeVisible()
    await page.locator('[data-part=hero]').click()
    await expect.poll(async () => (await wideLayers()).part).toBe('hero')
    await page.locator('[data-split]').click()
    await expect.poll(async () => (await state()).layers.twins.part).toBe('board')
    expect((await state()).layers.twins.scene).toBe('raceWin')
    // none has no options section at all
    await page.locator('[data-scene=none]').click()
    await expect(page.locator('[data-scene-options]')).toHaveCount(0)
  })

  test('twins: choosing a win screen picks a part a twin can show; QR has no layout options', async ({ page }) => {
    await page.goto('/control')
    await page.locator('[data-output-tab=twins]').click()
    await page.locator('[data-scene=cupWin]').click()
    await expect.poll(async () => (await state()).layers.twins.part).toBe('hero')
    await expect(page.locator('[data-part]')).toHaveText(['Hero', 'Board'])
    await page.locator('[data-scene=qr]').click()
    await expect(page.locator('[data-no-options]')).toBeVisible()
  })

  test('background and overlays: one segmented row, toggles and player chips (not on twins)', async ({ page }) => {
    await page.goto('/control')
    for (const [label, id] of [['A · Sky', 'A'], ['B · Icons', 'B'], ['C · Stickers', 'C'], ['None', 'none']] as const) {
      // "None" is also a scene, so address the segmented row by its group
      const b = page.getByRole('group', { name: 'Background' }).getByRole('button', { name: label, exact: true })
      await b.click()
      await expect.poll(async () => (await wideLayers()).background).toBe(id)
      await expect(b).toHaveAttribute('aria-pressed', 'true')
    }
    await page.locator('[data-overlay=trackCard]').click()
    await expect.poll(async () => (await wideLayers()).trackCard).toBe(true)
    await page.locator('[data-overlay=lowerThirds]').click()
    await expect.poll(async () => (await wideLayers()).lowerThirds.on).toBe(true)
    await page.locator('[data-lt-player="1"]').click()
    await expect.poll(async () => (await wideLayers()).lowerThirds.players).toEqual([0, 2, 3])
    await page.locator('[data-lt-player="1"]').click()
    await expect.poll(async () => (await wideLayers()).lowerThirds.players).toEqual([0, 1, 2, 3])
    await page.locator('[data-output-tab=twins]').click()
    await expect(page.locator('[data-lt-player]')).toHaveCount(0)
  })

  test('tournament scenes: bracket and matches appear, with the match and matches-set controls', async ({ page }) => {
    await command({ type: 'createTournament', name: 'T' })
    await page.goto('/control')
    await page.getByRole('button', { name: 'Cup win' }).click()
    await page.locator('[data-part=hero]').click()
    await expect.poll(async () => (await wideLayers()).part).toBe('hero')
    await page.locator('select[name=matchRef]').selectOption('previous')
    await expect.poll(async () => (await wideLayers()).matchRef).toBe('previous')
    await page.locator('[data-split]').click()
    await expect.poll(async () => (await state()).layers.twins.part).toBe('board')
    await page.getByRole('button', { name: 'Matches', exact: true }).click()
    await expect(page.locator('[data-matches-controls]')).toBeVisible()
    await page.locator('[data-set-round="0"]').click()
    await expect.poll(async () => (await wideLayers()).matchSet).toEqual({ rounds: [0] })
    await page.locator('[data-set-all]').click()
    await expect.poll(async () => (await wideLayers()).matchSet).toEqual({})
    await page.locator('input[aria-label="From match"]').fill('2')
    await page.locator('input[aria-label="From match"]').press('Tab')
    await expect.poll(async () => (await wideLayers()).matchSet?.range?.[0]).toBe(1)
    await expect(page.getByRole('button', { name: 'Bracket', exact: true })).toBeVisible()
  })
})
